### ISSUE TITLE
Undefined method `element_children' for nil:NilClass (NoMethodError) in parser.rb:273

### ISSUE THREAD

**Issue by nowakoo** [savonrb/wasabi#109] opened 2022-07-22 11:19 UTC
I try to call operations from WSDL file

`client.operations`

I receive the following error instead:
```
Traceback (most recent call last):
        12: from soap.rb:6:in `<main>'
        11: from /home/pinowakowski/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/savon-2.12.1/lib/savon/client.rb:28:in `operations'
        10: from /home/pinowakowski/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/wasabi-3.7.0/lib/wasabi/document.rb:66:in `soap_actions'
         9: from /home/pinowakowski/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/wasabi-3.7.0/lib/wasabi/document.rb:149:in `parser'
         8: from /home/pinowakowski/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/wasabi-3.7.0/lib/wasabi/document.rb:163:in `parse'
         7: from /home/pinowakowski/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/wasabi-3.7.0/lib/wasabi/parser.rb:63:in `parse'
         6: from /home/pinowakowski/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/wasabi-3.7.0/lib/wasabi/parser.rb:140:in `parse_operations'
         5: from /home/pinowakowski/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.7-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `each'
         4: from /home/pinowakowski/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.7-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `upto'
         3: from /home/pinowakowski/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.7-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `block in each'
         2: from /home/pinowakowski/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/wasabi-3.7.0/lib/wasabi/parser.rb:153:in `block in parse_operations'
         1: from /home/pinowakowski/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/wasabi-3.7.0/lib/wasabi/parser.rb:237:in `output_for'
/home/pinowakowski/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/wasabi-3.7.0/lib/wasabi/parser.rb:273:in `input_output_for': undefined method `element_children' for nil:NilClass (NoMethodError)
```

I am using Wasabi 3.7.0 with Savon 2.12.1
I tried also to use 3.4.0 with the same result

**Comment by Dounx** [comment] 2022-11-11 03:38
https://www.onvif.org/ver10/events/wsdl/event.wsdl

I use this WSDL file and then get this error too.

**Comment by pcai** [comment] 2024-10-01 19:30
looks like dupe of #61 and i cant repro in main, please reopen with another wsdl if this still persists

**Closed by pcai** 2024-10-01 19:30 UTC
